name: testing-github-actions
on:
  push:
    branches:
      - main
jobs:
  read-instructions:
    runs-on: windows-latest
    steps:
      - run: start powershell -ExecutionPolicy bypass -file ./TachyonPipelineLibrary/ReadXML.ps1
      - run: git config user.email "babirami@gmail.com"
      - run: git config user.name "abirami"
      - run: git commit -a -m "Commit to main repository"
      - run: git push origin HEAD:main --force
